version: '2.1'
services:
  database:
    restart: "no"
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "cake-factory"
#    networks:
#      backend:
#        aliases:
#          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
